#Site settings
title: Prinon Das
email: prinon.das@rwth-aachen.de
description: Traveller ~ Space lover ~ Foodie ~ Software-Engineer

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested